### ISSUE TITLE
1.0.5 init errors - Cannot initialize connector "es": Maximum call stack size exceeded

### ISSUE THREAD

**Issue by juanpujol** [strongloop-community/loopback-connector-elastic-search#43]
Updating from 1.0.4 to 1.0.5 throws this error when I try to start the app.

```
TypeError: Cannot create data source "elasticsearch-dev": Cannot initialize connector "es": Invalid apiVersion "2.x", expected a function or one of master, 1.x, 1.3, 1.2, 1.1, 1.0, 0.90
    at Object._.funcEnum (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/elasticsearch/src/lib/utils.js:356:11)
    at new Client (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/elasticsearch/src/lib/client.js:66:29)
    at ESConnector.connect (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-connector-es/lib/esConnector.js:103:19)
    at Object.module.exports.initialize (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-connector-es/lib/esConnector.js:29:30)
    at DataSource.setup (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-datasource-juggler/lib/datasource.js:337:19)
    at new DataSource (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-datasource-juggler/lib/datasource.js:114:8)
    at Registry.createDataSource (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback/lib/registry.js:349:12)
    at dataSourcesFromConfig (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback/lib/application.js:434:19)
    at EventEmitter.app.dataSource (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback/lib/application.js:233:14)
    at /Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-boot/lib/executor.js:178:9
    at /Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-boot/lib/executor.js:269:5
    at Array.forEach (native)
    at forEachKeyedObject (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-boot/lib/executor.js:268:20)
    at setupDataSources (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-boot/lib/executor.js:173:3)
    at execute (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-boot/lib/executor.js:32:3)
    at bootLoopBackApp (/Users/juan/Documents/Projects/bkn-buildings-api/node_modules/loopback-boot/index.js:140:3)
    at Object.<anonymous> (/Users/juan/Documents/Projects/bkn-buildings-api/server/server.js:21:1)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Object.<anonymous> (/Users/juan/.nvm/versions/v5.2.0/lib/node_modules/strongloop/node_modules/strong-supervisor/bin/sl-run.js:77:19)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at /Users/juan/.nvm/versions/v5.2.0/lib/node_modules/strongloop/lib/command.js:28:23
    at CommandLoader.run (/Users/juan/.nvm/versions/v5.2.0/lib/node_modules/strongloop/lib/loader.js:126:3)
```

Removing `apiVersion` from the datasource config bypasses the error.

But after fixing that I get this error:

`Cannot initialize connector "es": Maximum call stack size exceeded`

The only solution I've for now is to revert to 1.0.4

**Comment by juanpujol** [comment]
Check the temporary solution at #44 

Thanks @onstrike07
